# Generated by Django 4.0.3 on 2022-04-26 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrr_date', models.DateField()),
                ('mrr_no', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=100, null=True)),
                ('Body', models.CharField(max_length=100, null=True)),
                ('Lot_No', models.CharField(max_length=100, null=True)),
                ('Variant', models.CharField(max_length=100, null=True)),
                ('VIN', models.CharField(max_length=100, null=True)),
                ('Color', models.CharField(max_length=100, null=True)),
                ('Fuel', models.CharField(max_length=100, null=True)),
                ('Status', models.CharField(max_length=100, null=True)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
    ]
